create role authenticated;
create role anon;
create schema auth;
create table auth.users (id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
grant usage on schema auth, public to authenticated;
grant execute on function auth.uid() to authenticated;
create publication supabase_realtime;
create table public.node (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name varchar not null,
  parent_node bigint references public.node(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  content text,
  metadata jsonb
);
create table public.relationship (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  node_id_1 bigint references public.node(id) on delete cascade,
  relation_type varchar,
  user_id uuid not null references auth.users(id) on delete cascade,
  node_id_2 bigint references public.node(id) on delete cascade
);
create table public.settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  settings jsonb,
  user_id uuid not null references auth.users(id) on delete cascade
);
