-- The original node model was created in the hosted project before migrations
-- were tracked here. Recreate it for fresh local databases without changing
-- existing hosted tables.
do $$
begin
  if to_regclass('public.node') is null then
    create table public.node (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      name varchar not null,
      parent_node bigint references public.node(id) on delete cascade,
      user_id uuid references auth.users(id) on delete cascade,
      content text,
      metadata jsonb
    );
    alter table public.node enable row level security;
    create policy node on public.node using (auth.uid() = user_id);
    grant all on public.node to anon, authenticated, service_role;
  end if;

  if to_regclass('public.relationship') is null then
    create table public.relationship (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      node_id_1 bigint references public.node(id) on delete cascade,
      node_id_2 bigint references public.node(id) on delete cascade,
      relation_type varchar,
      user_id uuid not null references auth.users(id) on delete cascade
    );
    alter table public.relationship enable row level security;
    create policy relationship on public.relationship using (auth.uid() = user_id);
    grant all on public.relationship to anon, authenticated, service_role;
  end if;

  if to_regclass('public.settings') is null then
    create table public.settings (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      settings jsonb,
      user_id uuid not null references auth.users(id) on delete cascade
    );
    alter table public.settings enable row level security;
    create policy settings on public.settings using (auth.uid() = user_id);
    grant all on public.settings to anon, authenticated, service_role;
  end if;
end;
$$;
